default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: telegram_notifier_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: telegram_notifier_test
